services:

  web:
    build:
      context: .
      dockerfile: Dockerfile.development

    container_name: pixa-web
    restart: unless-stopped

    command: python manage.py runserver 0.0.0.0:8000

    ports:
      - "8000:8000"

    volumes:
      - ./src:/app

    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.development
