# Generated by Django 6.1 on 2026-09-15 15:33

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(max_length=100, validators=[utils.validators.NameValidator()]),
        ),
    ]
