# Generated by Django 6.1 on 2026-09-06 14:29

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(error_messages={'required:': 'Full name is required.'}, max_length=100, validators=[utils.validators.NameValidator()]),
        ),
    ]
