# Generated by Django 6.1 on 2026-09-21 17:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='slug',
        ),
        migrations.AddField(
            model_name='photo',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
